# Set unique port
quarkus.http.port=8081
quarkus.http.cors.enabled=true

# Keycloak Dev Services realm with 60-minute token lifetime
%dev.quarkus.keycloak.devservices.realm-path=../keycloak-realm.json

# Enforce authentication for MCP SSE
quarkus.http.auth.permission.mcp-endpoints.paths=/mcp,/mcp/*
quarkus.http.auth.permission.mcp-endpoints.policy=authenticated

# Enable MCP logging
quarkus.mcp.server.traffic-logging.enabled=true
quarkus.mcp.server.traffic-logging.text-limit=1000

# Log REST client request-response
quarkus.rest-client.logging.scope=request-response
